package ru.pokrov.auth.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import ru.pokrov.auth.daos.UserDao;
import ru.pokrov.auth.dtos.UserInfo;
import ru.pokrov.auth.entities.User;
import ru.pokrov.auth.utils.JwtTokenUtil;

import javax.persistence.EntityExistsException;

/**
 * UserService provide user's manipulations
 */
@Service
public class UserService implements UserDetailsService {

    @Autowired private UserDao userDao;
    @Autowired private PasswordEncoder passwordEncoder;
    @Autowired private JwtTokenUtil jwtTokenUtil;
    @Autowired private AuthenticationManager authenticationManager;

    /**
     * Generate auth token if user is valid
     * @param username username
     * @param password password
     * @return JWT authentication token
     * @throws AuthenticationException if user is not valid
     */
    public String login(String username, String password) throws AuthenticationException {
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(username, password));
        UserDetails userDetails = loadUserByUsername(username);
        return jwtTokenUtil.generateToken(userDetails);
    }

    /**
     * Register new user and add them to database
     * @param userInfo user to be registered
     * @return this user with autogenerated id or null if exists
     */
    public UserInfo signup(UserInfo userInfo) throws EntityExistsException {
        User userFromDb = userDao.findByUsername(userInfo.getUsername());
        if (userFromDb != null) throw new EntityExistsException();

        User user = new User();
        user.setActive(true);
        return update(user, userInfo);
    }

    /**
     * Update user information
     * @param user user to be changed
     * @param info new user information
     * @return changed user
     */
    public UserInfo update(User user, UserInfo info) {
        user.setFirstName(info.getFirstName());
        user.setLastName(info.getLastName());
        user.setBirthday(info.getBirthday());
        user.setUsername(info.getUsername());

        if (!info.getPassword().isEmpty())
            user.setPassword(passwordEncoder.encode(info.getPassword()));

        user = userDao.save(user);
        return UserInfo.of(user);
    }

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        return userDao.findByUsername(username);
    }
}
